### PR TITLE
Add tags and public flag to teams.

### PR DESCRIPTION
**Pull request by bernardoamc**
This PR is related with [this one](https://github.com/exercism/exercism.io/pull/2979)  from the `exercism.io` repo.

### CODE REVIEW

**Comment by bernardoamc** [comment]
@kytrinyx I have a problem generating `lifecycle_events`, can you use this change and try to generate the new `sql` files?

**Comment by kytrinyx** [comment]
I think we deleted lifecycle events. Let me check.

**Comment by kytrinyx** [comment]
Yepp:

> db/migrate/201605031827_drop_log_entries_and_lifecycle_events.rb

We should just delete the lifecycle events entirely.

**Comment by bernardoamc** [comment]
> I think we deleted lifecycle events. Let me check.

Ok, that makes sense now!

> We should just delete the lifecycle events entirely.

I can probably open a new PR in a few hours with these changes if you want.

**Comment by bernardoamc** [comment]
Now we can generate the new SQL files here. 🎉

**Comment by kytrinyx** [comment]
Merged in 714df4a76a66cbb754195e83320f378c80cf0726

**Comment by kytrinyx** [comment]
I generated the SQL and merged locally 🎉 Thank you!

**Pull request closed without merging**
