### PR TITLE
Regenerate seed data to remove all instances of mastery

### PR DESCRIPTION
**Pull request by mhelmetag**
Addresses issue #8 

@kytrinyx ,

I'm really uneasy to merge this because it looks like a lot changes... I must have something poorly configured. But it seems like any mention of `mastery` in `db/*.sql` has gone away which makes me hopeful...

Could you try `rake seeds:generate` again and see if you lose any mention of `mastery` in the three sql files in the db dir?

### CODE REVIEW

**Comment by kytrinyx** [comment]
I'll give it a go on my end.

**Comment by mhelmetag** [comment]
Awesome! Thanks!

**Comment by kytrinyx** [comment]
OK, so the problem is that the mastery column isn't dropped from the development database, and the seeds dumps the schema from there, before loading it into the seeds database. So we need to fix the migration first. I'll take a look at your PR for that.

**Comment by kytrinyx** [comment]
Fixed in 985cc9886eea978cb15bc726a260773c173c960e

**Comment by mhelmetag** [comment]
Awesomesauce!

**Pull request closed without merging**
