### PR TITLE
Remove Lifecycle Events.

### PR DESCRIPTION
**Pull request by bernardoamc**

### CODE REVIEW

**Comment by bernardoamc** [comment]
@kytrinyx Can you generate the `sql` versions? :)

**Comment by kytrinyx** [comment]
Yeah, totally!

**Comment by kytrinyx** [comment]
Generated and merged in 0db81114a40bf44a2c79f65359a27765c1cf1aa0

**Comment by bernardoamc** [comment]
Thanks @kytrinyx ! ❤️

**Pull request merged**
